version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/apps:cached
      - node_modules:/workspaces/apps/node_modules
    # Keep container running
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NODE_ENV=development
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "5173:5173"
      - "4173:4173"

volumes:
  node_modules: